SELECT FIRST_NAME,LAST_NAME,SALARY FROM employees WHERE SALARY > (SELECT SALARY FROM employees WHERE LAST_NAME='Bull');
SELECT FIRST_NAME,LAST_NAME FROM employees WHERE JOB_ID = (SELECT JOB_ID FROM jobs WHERE employees.JOB_ID = jobs.JOB_ID AND jobs.JOB_ID LIKE '%IT%');
SELECT FIRST_NAME,LAST_NAME FROM employees WHERE JOB_ID = (SELECT JOB_ID FROM jobs WHERE employees.JOB_ID = jobs.JOB_ID AND jobs.JOB_ID LIKE '%MGR%');
SELECT FIRST_NAME,LAST_NAME,SALARY FROM employees WHERE SALARY > (SELECT AVG(SALARY) FROM employees);
SELECT FIRST_NAME,LAST_NAME FROM employees WHERE SALARY in (SELECT MIN_SALARY FROM jobs WHERE jobs.JOB_ID = employees.EMPLOYEE_ID);
SELECT FIRST_NAME,LAST_NAME,SALARY FROM employees WHERE SALARY in (SELECT MIN(SALARY) FROM employees GROUP BY DEPARTMENT_ID);
SELECT EMPLOYEE_ID , FIRST_NAME , LAST_NAME , (SELECT DEPARTMENT_NAME FROM departments WHERE employees.DEPARTMENT_ID = departments.DEPARTMENT_ID) AS 'Department Name' FROM employees;
SELECT * FROM (SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10) SUB ORDER BY EMPLOYEE_ID ASC;