SELECT FIRST_NAME,LAST_NAME,SALARY FROM employees WHERE SALARY BETWEEN 10000 AND 15000 AND DEPARTMENT_ID IN (30,100);
SELECT FIRST_NAME,LAST_NAME,HIRE_DATE FROM employees WHERE YEAR(HIRE_DATE) = '1987';
SELECT FIRST_NAME FROM employees WHERE FIRST_NAME LIKE '%c%' AND FIRST_NAME LIKE '%b%';
SELECT employees.LAST_NAME,employees.SALARY,jobs.JOB_TITLE FROM employees INNER JOIN jobs ON employees.JOB_ID=jobs.JOB_ID WHERE JOB_TITLE IN ('Programmer','Shipping Clerk') AND employees.SALARY NOT IN ('4500','10000', '15000');
SELECT LAST_NAME AS Last_name_in FROM employees WHERE LAST_NAME IN ('BLAKE','SCOTT','KING','FORD');