SELECT JOB_ID AS Job, COUNT(*) AS number_of_employees_with_the_same_job FROM employees GROUP BY JOB_ID;
SELECT MANAGER_ID, SALARY FROM employees HAVING SALARY = (SELECT MIN(SALARY) FROM employees);
SELECT SUM(SALARY) AS Total_salary, DEPARTMENT_ID FROM employees GROUP BY DEPARTMENT_ID;
SELECT AVG(SALARY) AS Average_of_salary,JOB_ID FROM employees WHERE JOB_ID NOT IN ('IT_PROG') GROUP BY JOB_ID;
SELECT JOB_ID,MAX(SALARY) FROM employees GROUP BY JOB_ID HAVING MAX(SALARY) >= 4000;
SELECT AVG(SALARY), DEPARTMENT_ID FROM employees GROUP BY DEPARTMENT_ID HAVING COUNT(DEPARTMENT_ID) > 10;